language: bash
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C /tmp/
- git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
script: "/tmp/testrunner/bin/run -c ."
env:
  global:
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
